### ISSUE TITLE
Connection refused on 1081 port

### ISSUE THREAD

**Issue by hypr2771** [docksal/service-juniper-vpn#4]
Hi guys !

First of all thanks for this image, I am pretty sure I am finally reaching the working stage !
My config file located at `~/.vpn/juniper-vpn-wrap.conf` :
```
[vpn]
host = VPN_URL
username = USERNAME
password = SECRET
socks_port = 1081
host_checker = 1
```

I run
```
docker run -d --name=juniper-vpn -p 127.0.0.1:1080:1080 -p 127.0.0.1:8080:8080 -v ~/.vpn/juniper-vpn-wrap.conf:/root/.juniper_networks/juniper-vpn-wrap.conf docksal/juniper-vpn
```

Looking at start up logs, everything seems fine
```
2019-01-31 17:43:30,978 CRIT Supervisor running as root (no user in config file)
2019-01-31 17:43:30,986 INFO RPC interface 'supervisor' initialized
2019-01-31 17:43:30,986 INFO supervisord started with pid 6
2019-01-31 17:43:31,989 INFO spawned: 'vpn' with pid 9
2019-01-31 17:43:31,990 INFO spawned: 'proxy-socks' with pid 10
2019-01-31 17:43:31,990 INFO spawned: 'proxy-http' with pid 11
Established listening socket on port 8080.
2019-01-31 17:43:32,995 INFO success: vpn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-01-31 17:43:32,995 INFO success: proxy-socks entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-01-31 17:43:32,996 INFO success: proxy-http entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

But the issue occurs when, from host machine, I try to use the Docker proxy
```
curl --proxy http://127.0.0.1:8080 https://ifconfig.co 
curl: (56) Received HTTP code 504 from proxy after CONNECT
curl --proxy socks5h://127.0.0.1:1080 https://ifconfig.co
curl: (7) Unable to receive initial SOCKS5 response.
```

In docker image logs', I can read this
```
2019/01/31 17:43:46 socat[12] E connect(5, AF=2 127.0.0.1:1081, 16): Connection refused
2019/01/31 17:43:49 socat[13] E connect(5, AF=2 127.0.0.1:1081, 16): Connection refused
```

I can guess something is not started correctly on Docker image's side but I feel you guys may know what it may be. In the meantime I will try to investigate more in depth into Polipo proxy to find where should I give a look.

In the meantime, all my respects ! :1st_place_medal:

**Comment by lmakarov** [comment]
@hypr2771 I think the VPN connection is not actually working in the container.

Try debugging by running the container with bash: 

```
docker run --rm -it -p 127.0.0.1:1080:1080 -p 127.0.0.1:8080:8080 -v ~/.vpn/juniper-vpn-wrap.conf:/root/.juniper_networks/juniper-vpn-wrap.conf docksal/juniper-vpn bash -li
```

then manually starting the VPN connection inside the container and check the output:

```
/root/.juniper_networks/juniper-vpn-wrap.py -c /root/.juniper_networks/juniper-vpn-wrap.conf
```

**Comment by lmakarov** [comment]
@hypr2771 were you able to figure this out?

**Comment by hypr2771** [comment]
@lmakarov damn, sorry for the delay mate.
I actually figured out that Pulse is badly configured in my company, thus cookies are set on a different endpoint than the login form...
So I tried various stuff, modified the code a bit and didn't managed to get it to work...

I just actually just gave up and solved the issue with Pulse Secure client instead in my Fedora version...
I will close the issue and sorry again for the delay !
Have a splendid evening.

**Comment by tomhatzer** [comment]
I do have the same problem right now. When debugging like @lmakarov said, the first command just runs 1 second and then kills the container again. I'm unable to enter the shell. There's also no error or output to the logs.

**Comment by lmakarov** [comment]
@tomhatzer try this instead for the first command (I also update the original [comment](#issuecomment-459465694)):

```
docker run --rm -it -p 127.0.0.1:1080:1080 -p 127.0.0.1:8080:8080 -v ~/.vpn/juniper-vpn-wrap.conf:/root/.juniper_networks/juniper-vpn-wrap.conf docksal/juniper-vpn bash -li
```

Unfortunately, I no longer have access to a Juniper VPN, so I'm not able to debug this myself.
